
militaryAlertLines = {"Hostiles!","Kill him!","Engaging target!","Contact!","Go, go!","Flank him!","Enemy!","Movement!","We got hostiles!","Enemy activity!","Huh?!"}
badGuysAlertLines = {"Gotcha!","You there!","Get him!","I'll make you suffer!","You're dead!","Kill him!","Choose the easy way!","Aha!","I'm gon' get ya'!","Hah!","Huh?!"}
regularAlertLines = {"You there!","Get him!","Aha!","Hah!","Huh?!","You're dead!","Aha!","Hah!","Huh?!"}
raidersAlertLines = {"Aha!","You there!","Get him!","Hey, a little piggy!","Yeeehaw!","Meat!","Kill him!","Groaaa!","I'm gon' get ya'!","Come here, meatboy!","You're gonna get roasted!","I'd have you for dinner!","Hah!","Huh?!"}


threatenFriendlyMessages = {"Watch where you're pointing that!", "You don't wanna threaten me!", "Hey, I'm friendly!", "You're about to make a big mistake!", "Don't point that at me!", "Friendly here, watch out!", "Lower your weapon!","Put the gun down!" }
unholsteredFriendlyMessages = {"Put away the weapon!", "Careful with that gun!", "Stop waving that gun!", "Holster your weapon!" }
pedWasRobbedMessages = {"Help! I'm being robbed!", "Robbery! Heelp!","This is all I have!", "Take it, it's all I have!", "Damn you, take this and leave me alone!","Don't hurt me! Take this...","Take this and let me go!","You wretched thief!","That's all I got!"}
pedWasAlreadyRobbedMessages = {"You already took all I got!", "I have nothing left!", "I don't have anything of value!", "I swear, I have nothing left!"}
threatenRobbingMessages = {"Please don't hurt me!", "Don't shoot!", "Please sir, no!", "Oh no!", "Not again!", "What do you want?"}
meleeThreatenedMessages = {"Gun!","Whoa!","Don't shoot!","Wait, mister..."}

traderChat ={"Check my wares! Maybe you'll find something you need.","You're looking to trade? Let me show you my wares!","Check my merchandise! C'mon, take a look!","Looking for something to buy? Search no more!","I might have something you need...","I'm a trader, not a philantrophist!","I sell all kind of goods. Take a look!","How much money you have?"}
dumpsitebosschat={"You're looking for a job?","You look like you could handle a punch... Perhaps I could use you.","I might have something for you to do..."}
campguardChat = {"Mind yourself inside the camp!","Lookin' to trade? Found the wrong guy, hehe...","Vehicle problems? A mechanic will help with that.","We're keeping a close watch on you!","We don't like your type 'round here","Solve your bussiness here and get lost!","No killing, no fighting, no loitering!","Were you bitten? Your pupils are kinda dilated...","Looking for the boss? Not me, not me!","They say there's a cure for the infection.","Don't you have somewhere else to be?","I don't want to talk right now","I'd do anything for a good meal right now!","Save your ammo. Shoot them in the head!","I barely got away from a group of robbers the other day!","Lock and load!","I don't trust you","I eat bandits for breakfast!"}
victimChat = {"No... Please! No...","*crying*","This is a nightmare, all this is a nightmare...","Please...","Please don't hurt me..."}
zombieChat = {"*angry moans*","*grunts*","*crazed mumbling*"}
civilianChat = {"Is that booze? Can I have a sip?","Please, do you have some food to spare?","I was thinking the same...","You look like you've seen a lot...","I've seen my family transforming in those monsters...","I drink to forget...","Be careful during the night, if you're heading out there","Be careful if you are going out there","There are good guys, and bad guys. Which one are you?","Psst! Got some smokes?","Thinking of them gives me the chills","I heard there are still some poker games around. Gambling will be the end of us!","I haven't seen you before...","I can't sleep anymore, I hear their screams every time I close my eyes","Life was hard before, but now it's unbearable...","I don't know for how long I can bare.","Sorry, what was that?","Do you hear them moaning? It gives me the shivers!","You thought of joining the Refugee Camp? Food, water and a safe place to sleep...","I heard there's a cure for the infection.","Are you infected?","My son had just landed at Easter Bay Airport when it all happened. Please, keep an eye out for him!","I heard rumors that the Establishment is hiding something","I'd do anything for a good meal right now!","I used to be a PR specialist before the Incident. How about you?","I was a plumber before all this","Never thought I'd live to see the End of Days!","I barely got away from a gang of robbers the other day!","I used to gamble in Las Venturas. Now it's just a hole in the ground.","I heard a big gunfight down the street last night","They keep getting stronger... crap, how do we get out of here?","*sigh* Look what I found! A broken bottle, the peeerfect weapon...", "I think I heard a train the other night...",
"There's an Establishment cargo plane circling all of San Andreas",
"They say that infection started in San Fierro",
"They say that bandits run a fighting ring in Las Venturas",
"Since they nuked Venturas, the whole place is a radiation dump hole!",
"Pack a rad suit if you're going to Venturas!",
"Avoid South Venturas. Radiation will melt your brain.",
"I heard mutant zeds were spotted around the nuke crater in Venturas",
"Do you have some wood and a bandage? I need to craft a splint",
"These camps are too busy. I'll go and build myself a shelter in the hills!",
"The whole Flint is bandit country nowadays",
"Joe Mills took his family to San Fierro through Whetstone. Never heard from them since!",
"Search for the Old Man. He has many answers!",
"I think I bought fake ZomboKleen the other day!",
"Have some rags? Gotta craft myself a backpack...",
"Two things are certain nowadays: infection and death.",
"Some gas stations still have fuel... you just need to look harder!",
"We can't stay here, we can't run away... What options do we get?",
"They say that the Establishment sinks any boat going too far from the coast",
"I heard that the Establishment would blow you to pieces if you try to leave San Andreas!","I heard raiders force people to fight in the cage in Hunter's Quarry" }
panicChat = {"Heeelp!","No, please no!","Go away!","Leave me alone!","Heeelp!","I'm scared, please nooo!","No! Don't touch me!"}
abusivecopChat = {"Move along!", "Nothing to see here, move along!","You want some too?","Do you have the guts to finish the job?","Get lost!","Move along! Official bussiness.","You talk too much","Are you infected?","Were you bitten? Your pupils are kinda dilated...","Don't you have somewhere else to be?","Do you ever get the feeling you're being watched through a sniper scope?","Piss off, don't get in my way!"}
refugeequesthubChat = { "We need water, food, fuel... Can you help?" , "The people here need any help available. Give us a hand!","You're looking for a job?","You look like you could take care of yourself... And others, perhaps?","I might have something for you to do..." }
refugeeChat = { "Life in the camp gets harder every day...", "Were you bitten? Your pupils are kinda dilated...","Have you seen my glasses?", "I heard that the Easter Bay quarantine camp was overrun. Zeds slaughtered them all...","If you're looking for a job, search for Aunt Helen","While we die of starvation here, the rich play poker in Bayside!", "Mind your words around the guards, or we'll all get punished.","Have you seen my daughter? I know she's alive!", "Is that booze? Can I have a sip?","Please, do you have some food to spare?","I was thinking the same...","You look like you've seen a lot...","I've seen my family transforming in those monsters...","Be careful during the night, if you're heading out there.","I haven't seen you before...","I can't sleep anymore, I hear their screams every time I close my eyes","Life was hard before, but now is unbearable...","I don't know for how long I can bare.","Sorry, what was that?","Do you hear them moaning? It gives me the shivers!","I never should have joined the Refugee Camp... The 'keepers kill us faster than the zombies!","Are you infected?","I got beaten for talking up to the guards...","Mind ye words 'round the 'keepers, or you'll end up in the cage.","Sally? Is that you?","I can't see without my glasses...","Before the Incident I was a chef","There are good guys, and bad guys. Which one are you?","I don't want to talk right now","My daughter went missing when it all happened. Please, keep an eye out for her!","I'd do anything for a good meal right now!","I used to be a bus driver before the Incident. How about you?","I was a plumber before all this","Never thought I'd live to see the End of Days!","Steve... Steve! Have you seen Steve?","I heard raiders force people to fight in the cage in Hunter's Quarry"}
peacekeepersChat = { "Get lost or I'll put you in the cage!", "We're keeping a close watch on you!", "We don't like your type around here, boy...", "Stay in line and you won't get hurt!", "Obey!", "Move along!","Get lost!","Go away, scum!","I don't like the looks of you, boy!","You talk too much","You look suspicious","Are you infected?","I was trained to bust heads, not babysit!","Don't mind my partner, he got here from LSPD","Do you ever get the feeling you're being watched through a sniper scope?","Don't you have somewhere else to be?","I don't want to talk right now","Save your ammo. Shoot them in the head!","A smile is cheaper than a bullet!","Lock and load!","I don't trust you","We is recruitin', go see Sgt. Stone to join!","Piss off, don't get in my way!",
"I'm told that MonoCorp is paying the Peacekeeper wages",
"MonoCorp brought their Air01 division to San Andreas", 
"I'm tired of these arrogant Suits snooping around", 
"The Underground scum will pay for their defiance!",
"I can't stand these fucking bureaucrats!",
"I just love the Peacekeeper life. We're clubbing all night long!",
"Don't get in the way of cleaners... They love burning people","I heard raiders force people to fight in the cage in Hunter's Quarry"}
suitChat = {"Hrrmpf..!","I don't like you","In the land of truth, the man with the facts is king","And I thought being transferred to San Andreas was a promotion...","You look suspicious","Get lost!","They told me this assignment will be like a holiday","You know too much","You talk too much","You've seen too much","Move along!","Shit, I forgot my night vision googles in the old bunker","Damn, I somehow lost my EM scanner","Don't you have somewhere else to be?","Do you ever get the feeling you're being watched through a sniper scope?","I don't want to talk right now","I don't trust you","I just love Site Echo assignments! The silence, the trees...",
"Since the Marines parked that carrier off-shore, supplies started flowing more easily","Air crashes became more frequent, we need to find the cause","Our aircraft keep getting shot down above Bone County and Tierra Robada"}
guardchat = {"*hhrmpf!*","*cough!*cough!*","I think I heard something!","Life's short out there, we need more people","*humming*","Huh...? What was that?","All this waiting, making me crazy...","The zeds grow restless, I can hear them!","Is that booze? Gimme a sip!","Psst! Got some smokes?","I drink to forget...","You talk too much","Are you infected?","A bullet a day keeps the zeds away","Do you ever get the feeling you're being watched through a sniper scope?","Don't you have something else to do?","I don't want to talk right now","I'd do anything for a good meal right now!","Save your ammo. Shoot them in the head!","Lock and load!","I don't trust you"}
raiderChat = {"Gotcha!", "*crazed laughter*", "Meat! Meat! Meat!", "Groaaaa..!","Bleed, little pig!","I'm hungry", "*crazed giggles*", "Meat! Red juicy meat!", "Hhrmpf...","*cough*cough*","I think I heard something...!","*humming*","What was that?","Is that booze? Gimme a sip!","Psst! Got a cig'?","Before the Incident I was a chef","Skraaaa pra-pra ta-ta-ta!","Ski-bi-di like boom!","I was eating people from before the Incident, hehe","When you're tired of hunting people, go play poker in the Quarry","You heard of the Cage Fighting in Hunter's Quarry?","You're alpha? Go and prove it in The Cage!","*howling*","My lunch just walked in!","Avoid South Venturas. Radiation will melt your brain.","I heard mutant zeds were spotted around the nuke crater in Venturas"}
CDFChat = {"I jumped in my BOV and evac'ed when SHTF!", "Watch out for hostiles!", "Don't try anything funny!", "I stand for the Free County of Red!", "Freemantle for President!", "Sheriff Gruber offers employment in Dillimore.", "The Freemantles will keep us safe!", "The zeds grow restless, I can hear them!","I heard there's a cure for the infection.","I like to play poker in Dillimore between assignments","Are you infected?","Psst! Got some smokes?","I drink to forget...","Do you hear them moaning? It gives me the shivers!","Don't you have something else to do?","Save your ammo. Shoot them in the head!","Keep your guns at ready!","Lock and load!","Keep your guns clean and loaded","I think I heard a train the other night...","There's an Establishment cargo plane circling all of San Andreas","They say that infection started in San Fierro","They say that bandits run a fighting ring in Las Venturas","Since they nuked Venturas, the whole place is a radiation dump hole!","Pack a rad suit if you're going to Venturas!","Avoid South Venturas. Radiation will melt your brain.","I heard mutant zeds were spotted around the nuke crater in Venturas","Do you have some wood and a bandage? I need to craft a splint","These camps are too busy. I'll go and build myself a shelter in the hills!","The whole Flint is bandit country nowadays","I think I bought fake ZomboKleen the other day!","Have some rags? Gotta craft myself a backpack...","Some gas stations still have fuel... you just need to look harder!","Don't get in the cleaner's way... They love burning people!","Our recruitors are always looking for new people. Not all recruits are prime material though..."}
banditChat = {"Those suckers in the scav camps, they scared of us...","*hhrmpf!*","*cough!*cough!*","I think I heard something!","Life's short out there, we need more people","*humming*","Huh...? What was that?","All this waiting, making me crazy...","Wanna play poker? Go to CJs mansion!","...so I told the fuckers: Hands up mo'fuckaz, 'dis a robbery!","Is that booze? Gimme a sip!","Psst! Got some smokes?","I heard old Derrik opened his Venturas fighting school again","I drink to forget...","The zeds grow restless, I can hear them!","You talk too much","Are you infected?","Do you ever get the feeling you're being watched through a sniper scope?","Don't you have something else to do?","I'd do anything for a good meal right now!","Save your ammo. Shoot them in the head!","A guy once told me to enjoy the little things in life. I shot him the morning after.","I can't remember the last time I had a good bourbon! Got any?","The day I shot my ex was the happiest in my life!","You better not go through my stuff back there!","I saw a man travelling with a bitten girl, claiming she was immune. She turned and ate him the next day, haha!","Lock and load!","Hey you! Come here, lemme tell you a joke!","Piss off, don't get in my way!","There's an Establishment cargo plane circling all of San Andreas", "They say that infection started in San Fierro", "Since they nuked Venturas, the whole place is a radiation dump hole!", "Pack a rad suit if you're going to Venturas!", "Avoid South Venturas. Radiation will melt your brain.", "I heard mutant zeds were spotted around the nuke crater in Venturas", "Do you have some wood and a bandage? I need to craft a splint", "These camps are too busy. I'll go and build myself a shelter in the hills!","I think I bought fake ZomboKleen the other day!", "Have some rags? Gotta craft myself a backpack...","Two things are certain nowadays: infection and death.", "Some gas stations still have fuel... you just need to look harder!", "We can't stay here, we can't run away... What options do we get?", "They say that the Establishment sinks any boat going too far from the coast", "I heard that the Establishment would blow you to pieces if you try to leave San Andreas!","I heard our boys brought down another Establishment aircraft. Here comes the booty!" }
refugeequesthubQuests = {"Our people are starving. Bring us some food cans.","We need more water! Can you bring us two water canisters?"}
refugeequesthubQuestsPositive = {"Great! Come back here when the job is done.","Very good. I'll wait for your return!"}
refugeequesthubQuestsNegative = {"Too bad. Let me know if you change your mind.","Well, we'll have to sort this out ourselves, then...","Okay, maybe someone else will help us..."}

--任务起始语言
QuestsIntroLines = {"Listen up...","Hear me out...","Hey, you...","Listen up...","Listen up..."}
QuestsPositive = {"Good!","Great!","Very good!"}
QuestsNegative = {"Too bad...","Okay then, go your way!","Let me know if you change your mind"}